library(MASS)
library(reshape2)
library(reshape)
id <- c(1, 1, 2, 2)
time <- c(1, 1, 2, 2)
x1 <- c(5, 3, 6, 2)
x2 <- c(6, 5, 1, 4)
mydata <- data.frame(id, time, x1, x2)
print(mydata)
# melt将数据堆叠到一列内
md <- melt(mydata, id = c("id", "time"))
cat("\n整合后:\n")
print(md)
# cast拆分数据
cast_data <- cast(md, id ~ variable, mean)
print(cast_data)
cast_data1 <- cast(md, id ~ time, mean)
print(cast_data1)
cast_data2 <- cast(md, id + time ~ variable, mean)
print(cast_data2)